export const navbarData = [
    {
        text: "Anasayfa",
        link: "/anasayfa",
        order: 1,
        css: "default-css",
        functionality: "mainButton",
    },
    {
        text: "Hizmetlerimiz",
        link: "/hizmetler",
        order: 2,
        css: "default-css",
        functionality: "parentButton",
        children: [
            {
                text: "Teknik Hizmetlerimiz",
                link: "/teknik-hizmetler",
                order: 1,
                css: "default-css",
                functionality: "parentButton",
                children: [
                    {
                        text: "Frontend Teknolojileri",
                        link: "/frontend-teknolojileri",
                        order: 1,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Backend Teknolojileri",
                        link: "/backend-teknolojileri",
                        order: 2,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "AWS Hizmetleri",
                        link: "/aws-hizmetleri",
                        order: 3,
                        css: "default-css",
                        functionality: "childButton",
                    },
                ],
            },
            {
                text: "Danışmanlık Hizmetlerimiz",
                link: "/danismanlik-hizmetleri",
                order: 2,
                css: "default-css",
                functionality: "parentButton",
                children: [
                    {
                        text: "Teknik Destek",
                        link: "/teknik-destek",
                        order: 1,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Bilgilendirme Hizmetleri",
                        link: "/bilgilendirme-hizmetleri",
                        order: 2,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Mentorluk Hizmetleri",
                        link: "/mentorluk-hizmetleri",
                        order: 3,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Danışmanlık Eğitimleri",
                        link: "/danismanlik-egitimleri",
                        order: 4,
                        css: "default-css",
                        functionality: "parentButton",
                        children: [
                            {
                                text: "Sertifikalı Danışmanlık Hizmeti",
                                link: "/sertifikali-danismanlik-hizmeti",
                                order: 1,
                                css: "default-css",
                                functionality: "childButton",
                            },
                            {
                                text: "Kurumsal Danışmanlık Hizmeti",
                                link: "/kurumsal-danismanlik-hizmeti",
                                order: 2,
                                css: "default-css",
                                functionality: "childButton",
                            },
                        ],
                    },
                    {
                        text: "Eğitim Öğretim Planlama",
                        link: "/egitim-ogretim-planlama",
                        order: 5,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Yazılım Danışmanlığı",
                        link: "/yazilim-danismanligi",
                        order: 6,
                        css: "default-css",
                        functionality: "childButton",
                    },
                    {
                        text: "Proje Danışmanlığı",
                        link: "/proje-danismanligi",
                        order: 7,
                        css: "default-css",
                        functionality: "childButton",
                    },
                ],
            },
            {
                text: "Hatalı Altyapı Onarımı",
                link: "/hatali-altyapi-onarimi",
                order: 3,
                css: "default-css",
                functionality: "childButton",
            },
        ],
    },
    {
        text: "Hakkımızda",
        link: "/hakkimizda",
        order: 3,
        css: "default-css",
        functionality: "parentButton",
        children: [
            {
                text: "Biz Kimiz?",
                link: "/biz-kimiz",
                order: 1,
                css: "default-css",
                functionality: "childButton",
            },
            {
                text: "Kurumsal",
                link: "/kurumsal",
                order: 2,
                css: "default-css",
                functionality: "childButton",
            },
            {
                text: "Referanslarımız",
                link: "/referanslarimiz",
                order: 3,
                css: "default-css",
                functionality: "parentButton",
                children: [
                    {
                        text: "Geçmiş Referanslar",
                        link: "/gecmis-referanslar",
                        order: 1,
                        css: "default-css",
                        functionality: "parentButton",
                        children: [
                            {
                                text: "x referansı",
                                link: "/x-referansi",
                                order: 1,
                                css: "default-css",
                                functionality: "childButton",
                            },
                            {
                                text: "y referansı",
                                link: "/y-referansi",
                                order: 2,
                                css: "default-css",
                                functionality: "childButton",
                            },
                            {
                                text: "z referansı",
                                link: "/z-referansi",
                                order: 3,
                                css: "default-css",
                                functionality: "childButton",
                            },
                        ],
                    },
                    {
                        text: "Gelecek Referanslar",
                        link: "/gelecek-referanslar",
                        order: 2,
                        css: "default-css",
                        functionality: "parentButton",
                        children: [
                            {
                                text: "a referansı",
                                link: "/a-referansi",
                                order: 1,
                                css: "default-css",
                                functionality: "childButton",
                            },
                            {
                                text: "b referansı",
                                link: "/b-referansi",
                                order: 2,
                                css: "default-css",
                                functionality: "childButton",
                            },
                            {
                                text: "c referansı",
                                link: "/c-referansi",
                                order: 3,
                                css: "default-css",
                                functionality: "childButton",
                            },
                        ],
                    },
                ],
            },
            {
                text: "Vizyon",
                link: "/vizyon",
                order: 4,
                css: "default-css",
                functionality: "childButton",
            },
            {
                text: "Misyon",
                link: "/misyon",
                order: 5,
                css: "default-css",
                functionality: "childButton",
            },
        ],
    },
    {
        text: "İletişim",
        link: "/iletisim",
        order: 4,
        css: "default-css",
        functionality: "mainButton",
    },
    {
        text: "Kayıt Ol",
        link: "/kayit-ol",
        order: 5,
        css: "default-css",
        functionality: "mainButton",
    },
    {
        text: "Giriş Yap",
        link: "/giris-yap",
        order: 6,
        css: "default-css",
        functionality: "mainButton",
    },
];